CREATE TABLE PaymentReceipt (
    paymentReceiptID INT PRIMARY KEY GENERATED BY DEFAULT AS SEQUENCE,
    paymentDate TIMESTAMP NOT NULL,
    revenue INT NOT NULL,
    agentID INT,
    CONSTRAINT fk_agent_paymentreceipt FOREIGN KEY (agentID) REFERENCES Agent(agentID)
);
